services:
  - type: web
    name: kitchen-hub-backend
    env: python
    buildCommand: "cd server && pip install -r requirements.txt"
    startCommand: "cd server && gunicorn -c gunicorn_config.py app:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: kitchen-hub-db
          property: connectionString

  - type: web
    name: kitchen-hub-frontend
    env: static
    buildCommand: "cd client && npm install && npm run build"
    staticPublishPath: ./client/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: kitchen-hub-backend
          property: host

databases:
  - name: kitchen-hub-db
    databaseName: kitchen_hub
    user: kitchen_hub_user